### ISSUE TITLE
Attempting to save a guide for offline viewing causes the app to crash

### ISSUE THREAD

**Issue by amagh** [amagh/Sherpa#5]
Occurs due to a change in the ContentProvider and being properly implemented in the methods for inserting the author into the database.

```
FATAL EXCEPTION: 
Process: project.hikerguide, PID: 27276
android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: authors.username (code 1299)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
    at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1369)
    at project.hikerguide.data.generated.GuideProvider.insert(GuideProvider.java:371)
    at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
    at android.content.ContentResolver.insert(ContentResolver.java:1276)
    at project.hikerguide.utilities.ContentProviderUtils.insertModel(ContentProviderUtils.java:40)
    at project.hikerguide.utilities.OfflineGuideManager.cacheGuide(OfflineGuideManager.java:133)
    at project.hikerguide.utilities.OfflineGuideManager.access$200(OfflineGuideManager.java:29)
    at project.hikerguide.utilities.OfflineGuideManager$DownloadListener.removeDownloadTask(OfflineGuideManager.java:329)
    at project.hikerguide.utilities.OfflineGuideManager$3.onSuccess(OfflineGuideManager.java:273)
    at project.hikerguide.utilities.OfflineGuideManager$3.onSuccess(OfflineGuideManager.java:268)
    at com.google.firebase.storage.zzi.zzi(Unknown Source)
    at com.google.firebase.storage.zzz.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by amagh** [comment]
Resolved.
See: 42ae9bc
